spring:
  cloud:
    gateway:
      routes:
        - id: auth-route
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: users-route
          uri: http://localhost:8084
          predicates:
            - Path=/user/**
          filters:
            - AuthenticationFilter
        - id: letters-route
          uri: http://localhost:8083
          predicates:
            - Path=/letter/**
          filters:
            - AuthenticationFilter
        - id: packages-route
          uri: http://localhost:8082
          predicates:
            - Path=/package/**
          filters:
            - AuthenticationFilter
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
server:
  port: 8080